import type { IconType } from "react-icons";
import { FaReact, FaHtml5, FaCss3Alt, FaGit, FaGithub } from "react-icons/fa";
import { ClaudeIcon } from "./claude-icon";
import {
  SiTypescript,
  SiJavascript,
  SiTailwindcss,
  SiVite,
  SiEslint,
  SiPrettier,
  SiPnpm,
  SiBun,
  SiFlutter,
  SiFramer,
  SiZod,
  SiAxios,
  SiRadixui,
  SiPayloadcms,
  SiReact,
  SiAirtable,
  SiFormik,
  SiPython,
  SiGo,
  SiPhp,
  SiTensorflow,
  SiPytorch,
  SiDocker,
  SiAmazon,
  SiPostgresql,
  SiMysql,
  SiVuedotjs,
  SiBootstrap,
  SiLaravel,
} from "react-icons/si";
import {
  TbRoute,
  TbDatabase,
  TbTable,
  TbInfinity,
  TbHandGrab,
  TbAtom2,
  TbLanguage,
  TbComponents,
  TbLayoutDashboard,
  TbClipboardList,
  TbCalendar,
  TbApi,
  TbCode,
  TbBraces,
  TbAlertTriangle,
  TbGitBranch,
  TbGitCommit,
  TbFilter,
  TbNetwork,
  TbCashRegister,
  TbWorld,
  TbMail,
  TbShieldCheck,
  TbBrain,
  TbEdit,
  TbPhoto,
  TbMedicalCross,
  TbCopy,
  TbSettings,
  TbFlame,
  TbDots,
  TbLink,
  TbBook,
  TbTool,
  TbSpider,
  TbArrowsShuffle,
  TbCpu,
  TbAccessible,
  TbAlpha,
} from "react-icons/tb";

export const skillIcons: Record<string, IconType> = {
  "React.js": FaReact,
  TypeScript: SiTypescript,
  "JavaScript (ES6+)": SiJavascript,
  "Go (Golang)": SiGo,
  HTML5: FaHtml5,
  CSS3: FaCss3Alt,
  "Tailwind CSS": SiTailwindcss,
  Python: SiPython,
  PHP: SiPhp,
  SQL: TbDatabase,

  "TanStack Router": TbRoute,
  "TanStack Query": TbDatabase,
  "TanStack Table": TbTable,
  "TanStack Form": TbClipboardList,
  "TanStack Virtual": TbInfinity,
  "dnd-kit": TbHandGrab,
  Zustand: TbAtom2,
  Zod: SiZod,
  Yup: TbShieldCheck,
  i18n: TbLanguage,
  Motion: SiFramer,
  "React Bits": TbComponents,
  "Shadcn UI": TbLayoutDashboard,
  "Radix UI": SiRadixui,
  "React Hook Form": TbClipboardList,
  Formik: SiFormik,
  "date-fns": TbCalendar,
  Axios: SiAxios,
  Resend: TbMail,
  Airtable: SiAirtable,

  "React Native": SiReact,
  NativeWind: SiTailwindcss,
  "Reusable React Native": TbComponents,

  "Payload CMS": SiPayloadcms,
  "Neon DB (PostgreSQL)": TbDatabase,
  MongoDB: TbDatabase,
  PostgreSQL: SiPostgresql,
  MySQL: SiMysql,

  "RESTful API": TbApi,
  "REST APIs": TbApi,
  "async/await": TbCode,
  "JSON handling": TbBraces,
  "Error handling": TbAlertTriangle,

  "Git & GitHub": FaGit,
  Husky: TbGitBranch,
  ESLint: SiEslint,
  Prettier: SiPrettier,
  "Lint-Staged": TbFilter,
  Commitlint: TbGitCommit,
  Vite: SiVite,
  pnpm: SiPnpm,
  Bun: SiBun,

  "Claude AI": ClaudeIcon as IconType,
  "GitHub Copilot": FaGithub,

  "Flutter & Dart": SiFlutter,
  "POS Systems": TbCashRegister,
  "Network Config": TbNetwork,

  // ML & AI Core
  TensorFlow: SiTensorflow,
  PyTorch: SiPytorch,
  "LLM Workflows": TbBrain,
  "Prompt Engineering": TbEdit,
  "NLP Preprocessing": TbAlpha,
  "RAG Systems": TbCode,

  // Machine Learning Practice
  "Deep Learning": TbBrain,
  "Image Classification": TbPhoto,
  "Medical Image Segmentation": TbMedicalCross,
  "Data Augmentation": TbCopy,
  "Hyperparameter Tuning": TbSettings,
  "Model Optimization": TbFlame,

  // AI Infrastructure
  "Vector Databases": TbDots,
  Embeddings: TbDots,
  LangChain: TbLink,
  "Multi-step Chaining": TbLink,
  "RAG Pipelines": TbCode,
  "Knowledge Grounding": TbBook,

  // Data & ML Operations
  "Data Pipelines": TbCode,
  "Feature Engineering": TbTool,
  "Web Scraping (Selenium)": TbSpider,
  "ETL Processes": TbArrowsShuffle,
  "Experiment Tracking": TbClipboardList,
  "Data Versioning": TbGitBranch,

  // DevOps & Cloud
  Docker: SiDocker,
  "AWS (Batch, S3, etc.)": SiAmazon,
  "CI/CD (GitHub Actions)": TbGitCommit,
  "GPU Optimization": TbCpu,
  "Mixed-Precision Training": TbAtom2,
  "Distributed Computing": TbNetwork,

  // Web Development
  "Vue.js": SiVuedotjs,
  Bootstrap: SiBootstrap,
  Laravel: SiLaravel,
  "WCAG 2.0AA Accessibility": TbAccessible,

  // Natural Languages
  "English (Native)": TbLanguage,
  "German (B2)": TbLanguage,
  "Turkish (B1)": TbLanguage,
  Arabic: TbWorld,
  English: TbWorld,
  Turkish: TbWorld,
};
